fix!: images not loading
Current Known Issues Still:

1. Copying a Tab item reports error.
```log

AttributeError at /admin/cms/page/copy-plugins/
'CMSPlugin' object has no attribute 'cmsplugin_ptr_id'
Request Method:	POST
Request URL:	http://localhost:8000/admin/cms/page/copy-plugins/?cms_path=%2Ftest%2Ftabs-cards-slideshow%2F%3Fedit
Django Version:	4.2.9
Exception Type:	AttributeError
Exception Value:
'CMSPlugin' object has no attribute 'cmsplugin_ptr_id'
Exception Location:	/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py, line 383, in __set__
Raised during:	cms.admin.placeholderadmin.copy_plugins
Python Executable:	/usr/local/bin/python3
Python Version:	3.11.13
Python Path:
['/code',
 '/usr/local/lib/python311.zip',
 '/usr/local/lib/python3.11',
 '/usr/local/lib/python3.11/lib-dynload',
 '/usr/local/lib/python3.11/site-packages']
Server time:	Tue, 12 Aug 2025 18:10:12 -0500
Traceback Switch to copy-and-paste view
/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py, line 55, in inner
        return inner     else:         @wraps(get_response)         def inner(request):             try:
                response = get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^ …
            except Exception as exc:                 response = response_for_exception(request, exc)             return response         return inner
Local vars
/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py, line 197, in _get_response
        if response is None:             wrapped_callback = self.make_view_atomic(callback)             # If it is an asynchronous view, run it in a subthread.             if iscoroutinefunction(wrapped_callback):                 wrapped_callback = async_to_sync(wrapped_callback)             try:
                response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
            except Exception as e:                 response = self.process_exception_by_middleware(e, request)                 if response is None:                     raise         # Complain if the view returned None (a common error).
Local vars
/usr/local/lib/python3.11/site-packages/django/utils/decorators.py, line 134, in _wrapper_view
                    if result is not None:                         return result                 if hasattr(middleware, "process_view"):                     result = middleware.process_view(request, view_func, args, kwargs)                     if result is not None:                         return result                 try:
                    response = view_func(request, *args, **kwargs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
                except Exception as e:                     if hasattr(middleware, "process_exception"):                         result = middleware.process_exception(request, e)                         if result is not None:                             return result                     raise
Local vars
/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py, line 62, in _wrapper_view_func
    def _wrapper_view_func(request, *args, **kwargs):         # Ensure argument looks like a request.         if not hasattr(request, "META"):             raise TypeError(                 "never_cache didn't receive an HttpRequest. If you are "                 "decorating a classmethod, be sure to use @method_decorator."             )
        response = view_func(request, *args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        add_never_cache_headers(response)         return response     return _wrapper_view_func
Local vars
/usr/local/lib/python3.11/site-packages/django/contrib/admin/sites.py, line 242, in inner
                # importing django.contrib.auth.models.User (unrelated model).                 from django.contrib.auth.views import redirect_to_login                 return redirect_to_login(                     request.get_full_path(),                     reverse("admin:login", current_app=self.name),                 )
            return view(request, *args, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        if not cacheable:             inner = never_cache(inner)         # We add csrf_protect here so this function can be used as a utility         # function for any view, without having to repeat 'csrf_protect'.         if not getattr(view, "csrf_exempt", False):
Local vars
/usr/local/lib/python3.11/site-packages/django/utils/decorators.py, line 46, in _wrapper
        # bound_method has the signature that 'decorator' expects i.e. no         # 'self' argument, but it's a closure over self so it can call         # 'func'. Also, wrap method.__get__() in a function because new         # attributes can't be set on bound method objects, only on functions.         bound_method = wraps(method)(partial(method.__get__(self, type(self))))         for dec in decorators:             bound_method = dec(bound_method)
        return bound_method(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
    # Copy any attributes that a decorator adds to the function it decorates.     for dec in decorators:         _update_method_wrapper(_wrapper, dec)     # Preserve any existing attributes of 'method', including the name.     update_wrapper(_wrapper, method)
Local vars
/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py, line 43, in inner
                    "Method Not Allowed (%s): %s",                     request.method,                     request.path,                     response=response,                     request=request,                 )                 return response
            return func(request, *args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        return inner     return decorator
Local vars
/usr/local/lib/python3.11/site-packages/django/views/decorators/clickjacking.py, line 38, in wrapper_view
    @xframe_options_sameorigin     def some_view(request):         ...     """     @wraps(view_func)     def wrapper_view(*args, **kwargs):
        resp = view_func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ …
        if resp.get("X-Frame-Options") is None:             resp["X-Frame-Options"] = "SAMEORIGIN"         return resp     return wrapper_view
Local vars
/usr/local/lib/python3.11/contextlib.py, line 81, in inner
        """         return self     def __call__(self, func):         @wraps(func)         def inner(*args, **kwds):             with self._recreate_cm():
                return func(*args, **kwds)
                           ^^^^^^^^^^^^^^^^^^^ …
        return inner class AsyncContextDecorator(object):     "A base class or mixin that enables async context managers to work as decorators."
Local vars
/usr/local/lib/python3.11/site-packages/cms/admin/placeholderadmin.py, line 393, in copy_plugins
        if not target_language or target_language not in get_language_list():             return HttpResponseBadRequest(force_str(_("Language must be set to a supported language!")))         copy_to_clipboard = target_placeholder.pk == request.toolbar.clipboard.pk         source_plugin_id = request.POST.get('source_plugin_id', None)         if copy_to_clipboard and source_plugin_id:
            new_plugin = self._copy_plugin_to_clipboard(
                               …
                request,                 source_placeholder,                 target_placeholder,             )             new_plugins = [new_plugin]         elif copy_to_clipboard:
Local vars
/usr/local/lib/python3.11/site-packages/cms/admin/placeholderadmin.py, line 440, in _copy_plugin_to_clipboard
        if not self.has_copy_plugins_permission(request, old_plugins):             message = _('You do not have permission to copy these plugins.')             raise PermissionDenied(force_str(message))         # Empty the clipboard         target_placeholder.clear()
        plugin_pairs = copy_plugins.copy_plugins_to(
                             …
            old_plugins,             to_placeholder=target_placeholder,             to_language=target_language,         )         return plugin_pairs[0][0]
Local vars
/usr/local/lib/python3.11/site-packages/cms/utils/copy_plugins.py, line 19, in copy_plugins_to
        old_parent = old_plugins[0].parent         for old_plugin in old_plugins:             if old_plugin.parent == old_parent:                 old_plugin.parent = old_plugin.parent_id = None     new_plugins = []     for old in old_plugins:         new_plugins.append(
            old.copy_plugin(to_placeholder, to_language or old.language,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
                            old_parent_cache, no_signals))     if new_plugins and parent_plugin_id:         from cms.models import CMSPlugin         parent_plugin = CMSPlugin.objects.get(pk=parent_plugin_id)         for idx, plugin in enumerate(new_plugins):
Local vars
/usr/local/lib/python3.11/site-packages/cms/models/pluginmodel.py, line 345, in copy_plugin
        new_plugin.save()         if plugin_instance:             # get a new instance so references do not get mixed up             plugin_instance = plugin_instance.__class__.objects.get(pk=plugin_instance.pk)             plugin_instance.pk = new_plugin.pk             plugin_instance.id = new_plugin.pk             plugin_instance.placeholder = target_placeholder
            plugin_instance.cmsplugin_ptr = new_plugin
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
            plugin_instance.language = target_language             plugin_instance.parent = new_plugin.parent             plugin_instance.depth = new_plugin.depth             plugin_instance.path = new_plugin.path             plugin_instance.numchild = new_plugin.numchild             plugin_instance._no_reorder = True
Local vars
/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py, line 383, in __set__
                field                 for field in opts.concrete_fields                 if field.primary_key and field.remote_field             ]             for field in inherited_pk_fields:                 rel_model_pk_name = field.remote_field.model._meta.pk.attname                 raw_value = (
                    getattr(value, rel_model_pk_name) if value is not None else None
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
                )                 setattr(instance, rel_model_pk_name, raw_value) class ReverseOneToOneDescriptor:     """
```
2. Creating pair of Tab items (with tab image, and content of picture plugin and text plugin), publishing page (works, i see my content published), then editing page, remvoes the content I just added.